blueprint:
  name: Upozornění na předpověď počasí
  description: Odeslat přizpůsobitelné upozornění na dnešní a zítřejší předpověď počasí.
  domain: automation
  input:
    weather_entity:
      name: Entita Počasí
      description: Integrace počasí, kterou používáte.
      selector:
        entity:
          filter:
            - domain: weather
            
    notify_device:
      name: Zařízení k upozornění
      description: Zařízení musí mít oficiální aplikaci Home Assistant, aby mohlo přijímat upozornění
      selector:
        device:
          multiple: true
          integration: mobile_app
          
    time:
      name: Čas spuštění
      description: Čas spuštění automatizace a odeslání upozornění.
      selector:
        time:

    notification_title:
      name: Název upozornění (Volitelné)
      description: Název upozornění
      default: "Předpověď počasí"

    notify_message:
      name: Dnešní Upozornění Počasí
      description: >-
        Příklad, jak bude počasí zobrazeno. Budou použity jednotky nastavené ve vaší integraci počasí.
        
        Podmínka: Prší
        
        Teplota: 8.4 // 4.0 °C
        
        Srážky: 8.6 mm
        
        Rychlost větru: 24.1 km/h // Směr větru: 273
      default: condition
      selector:
        select:
          mode: list
          multiple: true
          options:
            - label: Stav počasí
              value: "condition"
            - label: Teplota
              value: "temperature"
            - label: Srážky
              value: "precipitation"
            - label: Vítr
              value: "wind"
 
# Vstup pro to, zda je předpověď na zítřek přidána k zprávě o upozornění. Pokud je zvoleno "ne", není přidána.
    tomorrow_message:
      name: Zítřejší Upozornění Počasí
      description: >-
        Příklad, jak bude počasí zobrazeno. Budou použity jednotky nastavené ve vaší integraci počasí.
        
        Zítra: Deštivo, Teplota: 13.2 // 11.7 °C, Srážky: 2.5 mm
      default: tomorrow
      selector:
        select:
          mode: dropdown
          options:
            - label: Ano - poslat informace o zítřejším počasí
              value: "tomorrow"
            - label: Ne - neposílat informace o zítřejším počasí
              value: "noTomorrow"

    lovelace_path:
      name: Lovelace panel
      description: URL cesty k panelu Lovelace, který se má otevřít po kliknutí na upozornění.
      selector:
        text:

variables:
  notify_device: !input notify_device
  weather_entity: !input weather_entity
  notification_title: !input notification_title
  time: !input time
  device_id: !input notify_device
  notify_message: !input notify_message
  tomorrow_message: !input tomorrow_message
  lovelace_path: !input lovelace_path
  
trigger:
  platform: time
  at: !input time

action:
# Volá službu předpovědi.
  - service: weather.get_forecasts
    data:
      type: daily
    target:
      entity_id: !input weather_entity
    response_variable: daily
    
  - variables:
      weather_entity: !input weather_entity
      forecast: "{{ daily[weather_entity].forecast }}"
      icon: >- # Nastaví ikonu upozornění (na androidu) na základě dnešní předpovědi.
        {% set cond_now = forecast[0].condition %}{% if cond_now == 'cloudy' %}mdi:clouds{% elif cond_now == 'fog' %}mdi:weather-fog{% elif cond_now == 'hail' %}mdi:weather-hail{% elif cond_now == 'lightning' %}mdi:weather-lightning{% elif cond_now == 'lightning-rainy' %}mdi:weather-lightning-rainy{% elif cond_now == 'partlycloudy' %}mdi:weather-partly-cloudy{% elif cond_now == 'pouring' %}mdi:weather-pouring{% elif cond_now == 'rainy' %}mdi:weather-rainy{% elif cond_now == 'snowy' %}mdi:weather-snowy{% elif cond_now == 'snowy-rainy' %}mdi:weather-snowy-rainy{% elif cond_now == 'sunny' %}mdi:weather-sunny{% elif cond_now == 'windy' %}mdi:weather-windy{% elif cond_now == 'windy-variant' %}mdi:weather-windy-variant{% elif cond_now == 'exceptional' %}mdi:cloud-alert{% else %}mdi:sun-thermometer{% endif %}
 
# Odeslání upozornění do aplikace. Opakuje se pro každé zařízení.
  - repeat:
      for_each: !input notify_device
      sequence: 
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ notification_title }}"
            message: >-
              {% set weather = weather_entity %}
              {% for message in notify_message %}
                {% if "condition" in message %}Podmínka: {{ (forecast[0].condition).capitalize() }}{% endif %}{% if "temperature" in message %}Teplota: {{forecast[0].temperature}} // {{forecast[0].templow}} {{ state_attr(weather,'temperature_unit') }}{% endif %}{% if "precipitation" in message %}Srážky: {{forecast[0].precipitation}} {{ state_attr(weather,'precipitation_unit') }}{% endif %}{% if "wind" in message %}Rychlost větru: {{forecast[0].wind_speed}} {{ state_attr(weather,'wind_speed_unit') }} // Směr větru: {{forecast[0].wind_bearing}}{% endif %}
              {% endfor %}
      
              {% if tomorrow_message == 'tomorrow' %}Zítra: {{ (forecast[1].condition).capitalize() }}, Teplota: {{forecast[1].temperature}} // {{forecast[1].templow}} {{ state_attr(weather,'temperature_unit') }}, Srážky: {{forecast[1].precipitation}} {{ state_attr(weather,'precipitation_unit') }}
              {% endif %}
            data:
              notification_icon: "{{ icon }}"
              clickAction: 
                action: "URI"
                title: "Otevřít panel Lovelace"
                uri: "/lovelace/{{ lovelace_panel }}"
