blueprint:
  name: Upozornění na předpověď počasí
  description: Odeslat přizpůsobitelné upozornění na dnešní a zítřejší předpověď počasí.
  domain: automation
  input:
    weather_entity:
      name: Entita Počasí
      description: Integrace počasí, kterou používáte.
      selector:
        entity:
          filter:
            - domain: weather
            
    notify_target:
      name: Cílová služba oznámení
      description: Vyberte službu oznámení, například notify.upozorneni.
      selector:
        target:
          entity:
            domain: notify

    time:
      name: Čas spuštění
      description: Čas spuštění automatizace a odeslání upozornění.
      selector:
        time:

    notification_title:
      name: Název upozornění (Volitelné)
      description: Název upozornění
      default: "Předpověď počasí"

    notify_message:
      name: Upozornění Počasí
      description: >-
        Příklad, jak bude počasí zobrazeno. Budou použity jednotky nastavené ve vaší integraci počasí.
        
        Podmínka: Prší
        
        Teplota: 8.4 // 4.0 °C
        
        Srážky: 8.6 mm
        
        Rychlost větru: 24.1 km/h // Směr větru: 273
      default: condition
      selector:
        select:
          mode: list
          multiple: true
          options:
            - label: Stav počasí
              value: "condition"
            - label: Teplota
              value: "temperature"
            - label: Srážky
              value: "precipitation"
            - label: Vítr
              value: "wind"
 
    forecast_day:
      name: Den předpovědi
      description: Zda poslat dnešní nebo zítřejší předpověď počasí.
      selector:
        select:
          options:
            - label: Dnes
              value: "today"
            - label: Zítra
              value: "tomorrow"

variables:
  weather_entity: !input weather_entity
  notification_title: !input notification_title
  time: !input time
  notify_target: !input notify_target
  notify_message: !input notify_message
  forecast_day: !input forecast_day
  
trigger:
  platform: time
  at: !input time

action:
  - service: weather.get_forecasts
    data:
      type: daily
    target:
      entity_id: !input weather_entity
    response_variable: daily
    
  - variables:
      weather_entity: !input weather_entity
      forecast: "{{ daily[weather_entity].forecast }}"
      icon: >-
        {% set cond_now = forecast[0].condition %}
        {% if cond_now == 'cloudy' %}mdi:clouds
        {% elif cond_now == 'fog' %}mdi:weather-fog
        {% elif cond_now == 'hail' %}mdi:weather-hail
        {% elif cond_now == 'lightning' %}mdi:weather-lightning
        {% elif cond_now == 'lightning-rainy' %}mdi:weather-lightning-rainy
        {% elif cond_now == 'partlycloudy' %}mdi:weather-partly-cloudy
        {% elif cond_now == 'pouring' %}mdi:weather-pouring
        {% elif cond_now == 'rainy' %}mdi:weather-rainy
        {% elif cond_now == 'snowy' %}mdi:weather-snowy
        {% elif cond_now == 'snowy-rainy' %}mdi:weather-snowy-rainy
        {% elif cond_now == 'sunny' %}mdi:weather-sunny
        {% elif cond_now == 'windy' %}mdi:weather-windy
        {% elif cond_now == 'windy-variant' %}mdi:weather-windy-variant
        {% elif cond_now == 'exceptional' %}mdi:cloud-alert
        {% else %}mdi:sun-thermometer
        {% endif %}
 
  - service: !input notify_target
    data:
      title: "{{ notification_title }}"
      message: >-
        {% set weather = weather_entity %}
        {% if forecast_day == 'tomorrow' %}
          {% set forecast_index = 1 %}
        {% else %}
          {% set forecast_index = 0 %}
        {% endif %}
        {% set condition_translations = {
          'cloudy': 'zataženo',
          'fog': 'mlha',
          'hail': 'krupobití',
          'lightning': 'blýskat',
          'lightning-rainy': 'bleskovo-deštivě',
          'partlycloudy': 'částečně oblačno',
          'pouring': 'liják',
          'rainy': 'deštivo',
          'snowy': 'sněžení',
          'snowy-rainy': 'sněhově-deštivo',
          'sunny': 'slunečno',
          'windy': 'větrno',
          'windy-variant': 'větrno',
          'exceptional': 'na pováženou'
        } %}
        
        {% set today_date = as_timestamp(now()) | timestamp_custom("%d.%m.%Y") %}
        {% set tomorrow_date = as_timestamp(now() + timedelta(days=1)) | timestamp_custom("%d.%m.%Y") %}
        
        {% if forecast_day == 'today' %}
          {% set date_text = "Dnes " + today_date %}
        {% elif forecast_day == 'tomorrow' %}
          {% set date_text = "Zítra " + tomorrow_date %}
        {% endif %}
                       
        {% for message in notify_message %}
          {% if "condition" in message %}{{ date_text }} bude {{ condition_translations.get(forecast[forecast_index].condition, forecast[forecast_index].condition) }}{% endif %}{% if "temperature" in message %}Teplota: {{forecast[forecast_index].temperature}} // {{forecast[forecast_index].templow}} {{ state_attr(weather,'temperature_unit') }}{% endif %}{% if "precipitation" in message %}Srážky: {{forecast[forecast_index].precipitation}} {{ state_attr(weather,'precipitation_unit') }}{% endif %}{% if "wind" in message %}Rychlost větru: {{forecast[forecast_index].wind_speed}} {{ state_attr(weather,'wind_speed_unit') }}{% endif %}
        {% endfor %}
    data:
      notification_icon: "{{ icon }}"
